### ISSUE TITLE
Add support for posgresql

### ISSUE THREAD

**Issue by aisyar** [samanazadi1996/Sam.CleanArchitecture#2]
add multiple database support

**Comment by samanazadi1996** [comment]
> add multiple database support

Certainly, in future versions, features such as changing the database will be added to this Extention

**Comment by samanazadi1996** [comment]
close

**Comment by wilz055** [comment]
@samanazadi1996 any updates on this... or any simple documentation to migrate or switch to postgres db ?

**Comment by samanazadi1996** [comment]
@wilz055 

I will publish the document about the database as soon as possible.

**Comment by samanazadi1996** [comment]
@aisyar @wilz055 

In the latest version of our package (8.4.1), a new tool has been added for migrating or switching to a PostgreSQL database. Additionally, documentation for this tool has been created and is readily available. Please refer to the new documentation for more details on how to use this tool.
[Documentation](https://github.com/samanazadi1996/Sam.CleanArchitecture/blob/master/Documents/ConfigureDatabase.md)

**Comment by wilz055** [comment]
@samanazadi1996  thank you for the quick implementation.. many thanks to your template. much appreciated

**Comment by wilz055** [comment]
PostgreSQL :- Getting exception like datetime conversion, in File DefaultBasicUser.cs 
Line number 28,  await userManager.CreateAsync(defaultUser, "Sam@12345");

ArgumentException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array, range, or multirange. (Parameter 'value')

And also in 
[Doc](https://github.com/samanazadi1996/Sam.CleanArchitecture/blob/master/Documents/ConfigureDatabase.md) Requires some updates like folder change cd commands. Had to manually point to each folder inorder to migrate/switching  it

**Comment by samanazadi1996** [comment]
I have fixed this issue in this commit
https://github.com/samanazadi1996/Sam.CleanArchitecture/commit/ded668652dcd2bb5ac7cb871a47b42f086bc228d
 and it will not be encountered in future versions of the plugin. Additionally, I will continuously improve the documentation. Thank you for reporting the issue.

**Comment by samanazadi1996** [comment]
@wilz055 
It's better if these configurations are set up by the user themselves and customize the database according to their needs. If I include this in the template, users might assume that it is mandatory. However, I will definitely create documentation for it.
