### ISSUE TITLE
Small recommendations Not bug

### ISSUE THREAD

**Issue by nammadhu** [samanazadi1996/Sam.CleanArchitecture#3]
Hi @samanazadi1996 
You have done great move of good repo for beginners & saving a lot of time.
I jjust started looking, I have few suggestions, its not bug.
1> Add documentation of creating commands & query, you added little in nuget page
<img width="676" alt="image" src="https://github.com/samanazadi1996/Sam.CleanArchitecture/assets/3640748/a40997c9-7be8-4408-a800-fb629e921ba3">

a>Here mention folder as /Application/Features
b>after adding cli namespaces are going wrong ,so probly you might need to change cmd as to be like below
<img width="906" alt="image" src="https://github.com/samanazadi1996/Sam.CleanArchitecture/assets/3640748/0ad55571-cc3a-4316-ae69-0e2447ef1122">

For more reference you can check another repo, in which i used to work along
https://github.com/neozhu/CleanArchitectureCodeGenerator by neozhu

2>If possible integrate a client project like blazor (my preferred) with authentication so your repo will be full stack

I hope am not wrong in any sense, *IF ITS OKAY* theni will be observing more & sharing more n more feedbacks

**Comment by samanazadi1996** [comment]
Hello.

Thank you for your issue dear friend.

I checked it. And I must say it is a very interesting idea. I have added the templates now and it will definitely be available in the next version of the package

And also more templates are created for other parts of the project

**Comment by nammadhu** [comment]
ok i hope you mean, no automated commands(complete) exists for this repo.
Template means for description of package right? or anything else?

And as i was mentioning about client side & social login , i just added for blazor client(webassembly) with working google login and complete flow with api and created [PR](https://github.com/samanazadi1996/Sam.CleanArchitecture/pull/4) for the same

**Comment by nammadhu** [comment]
@samanazadi1996 It would be great if you please guide , how to add new entity , its command ,query,service or anymore through template/automated way...
