### ISSUE TITLE
SuggestionNotBug: Add More instructions like migrations which project had to be started something like that

### ISSUE THREAD

**Issue by nammadhu** [samanazadi1996/Sam.CleanArchitecture#5]
This was in my case, the reason is I made multiple startup projects so giving nn errors, so mention for ef migrations
step1>Set API project as startup project
step2>then specific commands like any of below
add-migration baseEntityChanges -Context ApplicationDbContext -project CleanArchitecture.Infrastructure.Persistence
    update-database -Context ApplicationDbContext 
 add-migration baseEntityChanges -Context FileManagerDbContext -project CleanArchitecture.Infrastructure.FileManager
     update-database -Context FileManagerDbContext 
 add-migration baseEntityChanges -Context IdentityContext -project CleanArchitecture.Infrastructure.Identity
      update-database -Context IdentityContext

<img width="894" alt="image" src="https://github.com/samanazadi1996/Sam.CleanArchitecture/assets/3640748/8de460ce-2d91-42c8-bc4f-4cb0d48e3b54">

Please close the bug once after adding notes or readme

**Comment by samanazadi1996** [comment]
Thank you for letting me know that I need such issues to complete the project documentation.
