### ISSUE TITLE
how to use automated template for creating command,query,service & more in all layers

### ISSUE THREAD

**Issue by nammadhu** [samanazadi1996/Sam.CleanArchitecture#6]
@samanazadi1996 It would be great if you please guide , how to add new entity , its command ,query,service or anymore through template/automated way...
[Continuation of ](https://github.com/samanazadi1996/Sam.CleanArchitecture/issues/3)

**Comment by nammadhu** [comment]
thats awesome man... I really love that much quick clip... Thanks @samanazadi1996 

WIll come up more trouble

**Comment by nammadhu** [comment]
I did quick test for my sample entity, mostly all working good... small observations for corrections,
1> Commands no issue template working good
2> Query & Pagelist both working good but namespaces are missing
<img width="907" alt="image" src="https://github.com/samanazadi1996/Sam.CleanArchitecture/assets/3640748/c22e34f2-86ae-467b-b965-38bba27da28e">
3>querypagelist here "D" letter missing documentaion,after adding it looks awesome
<img width="598" alt="image" src="https://github.com/samanazadi1996/Sam.CleanArchitecture/assets/3640748/955d4980-6e5a-4bf8-8ff2-050a3488e5ac">

cool will come up with more...

I also created repo, PR and adding more & more, if am wrong in any sense please correct me...

**Comment by samanazadi1996** [comment]
You must have already created the return type.
If you pay attention to the example of Products, this type is located in the domain layer.

> The document was also updated.
