### ISSUE TITLE
Make Id in BaseEntity Generic to accept int, guid or any other type

### ISSUE THREAD

**Issue by zaktecs** [samanazadi1996/Sam.CleanArchitecture#69]
Hi Sam,  
Thank you for the template. I'd like to use "int" or "GUID" as the ID for certain entities. Is it possible since the base class specifies `long` as the ID?

**Comment by samanazadi1996** [comment]
> Hi Sam,  
> Thank you for the template. I'd like to use "int" or "GUID" as the ID for certain entities. Is it possible since the base class specifies `long` as the ID?
> 

Hi,
This is just a template, and you can change the ID type depending on your project needs. This change won't cause any issues, and you can use either **int** or **GUID**

**Comment by samanazadi1996** [comment]
@zaktecs 
Generic BaseEntity was added in [this commit](https://github.com/samanazadi1996/Sam.CleanArchitecture/commit/28de85223debf5d78e3db7755a0df3a393dd6b61).

**Comment by zaktecs** [comment]
Thanks @samanazadi1996
