### ISSUE TITLE
NotBug, Enhancement: IFF possible & whenever possible, Multi-Tenant - roles management

### ISSUE THREAD

**Issue by nammadhu** [samanazadi1996/Sam.CleanArchitecture#7]
IFF possible & whenever possible, it would be great to have Multi-Tenant based administration/Auth  & with respective tenant multiple roles management, so this can be best full package kind of with almost all necessary scenarios.
#NotBug  #Enhancement

**Comment by samanazadi1996** [comment]
Please explain more if possible

**Comment by nammadhu** [comment]
Currently we dont have anything like tenant, usually in real time it always separated with tenents.
For an example scenario HospitalManagementSystem: where each hospital(tenant) will have its own roles(Doctor,Assistant,HOD,Nurse..), one hospital HOD(role) can be another  hospital(tenant) normal doctor(role)

Proably this needs to add tenantid in role management tables, similar already implemented in another repo where i used to interact. https://github.com/neozhu/CleanArchitectureWithBlazorServer
If possible I will only try to make , but you also can refer db schema.

So this single project can be easily multi-tenant & an open expansion for larger scenario cases

**Comment by samanazadi1996** [comment]
In that case, the project loses its simplicity. I believe these changes should be added by users based on their specific project needs
