### ISSUE TITLE
Change Tracking wrt item

### ISSUE THREAD

**Issue by nammadhu** [samanazadi1996/Sam.CleanArchitecture#72]
Since you nicely improved Audit Tracking, with that it wouyld be great to have some features like ,
1>Product id 7 ,its changes logged somewhere or in table like ProductHistory, which having like previous state to current state with value difference by . Usually we used to have triggers wrt each column in my earlier days,is smething better .
 2>On before product update,if i assign PrevStage to currentNewStage so instead of writing all columns again even if no changes, is any extension or some way which writes/updates only the changed columns.
  3>Hangfire with simple example
 These feature makes repository richer,as repo currently having all necessary contents especially with Simplicity
 @samanazadi1996

**Comment by samanazadi1996** [comment]
Hello @nammadhu 

Regarding the Audit Log implementation, this feature has been integrated into the project using two options: **MongoDB** and **EventStore**. Users can choose which of these systems they would like to use for storing changes.

For more information and details on how to utilize this feature, please refer to this document:
https://github.com/samanazadi1996/Sam.CleanArchitecture/blob/master/Documents/AuditLog.md
